theme: jekyll-theme-architect

title: CHUCK
description: SHARE

# Setup
name:         CHUCK PAGE
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown